apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zaproxies.zaproxy.owasp.org
spec:
  group: zaproxy.owasp.org
  names:
    kind: Zaproxy
    listKind: ZaproxyList
    plural: zaproxies
    singular: zaproxy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Zaproxy is the Schema for the zaproxies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ZaproxySpec defines the desired state of Zaproxy
          properties:
            attackType:
              type: string
            tragetIngress:
              type: string
            tragetNamespace:
              type: string
          required:
          - attackType
          - tragetIngress
          - tragetNamespace
          type: object
        status:
          description: ZaproxyStatus defines the observed state of Zaproxy
          properties:
            attackStatus:
              type: string
          required:
          - attackStatus
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
