kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zap-operator.fullname" . }}-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "zap-operator.name" . }}
    helm.sh/chart: {{ include "zap-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "zap-operator.fullname" . }}-sa
roleRef:
  kind: Role
  name: {{ include "zap-operator.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
