apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zap-operator.fullname" . }}-sa
  labels:
    app.kubernetes.io/name: {{ include "zap-operator.name" . }}
    helm.sh/chart: {{ include "zap-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
