// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/zaproxy/v1alpha1.Zaproxy":       schema_pkg_apis_zaproxy_v1alpha1_Zaproxy(ref),
		"./pkg/apis/zaproxy/v1alpha1.ZaproxySpec":   schema_pkg_apis_zaproxy_v1alpha1_ZaproxySpec(ref),
		"./pkg/apis/zaproxy/v1alpha1.ZaproxyStatus": schema_pkg_apis_zaproxy_v1alpha1_ZaproxyStatus(ref),
	}
}

func schema_pkg_apis_zaproxy_v1alpha1_Zaproxy(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Zaproxy is the Schema for the zaproxies API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/zaproxy/v1alpha1.ZaproxySpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/zaproxy/v1alpha1.ZaproxyStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/zaproxy/v1alpha1.ZaproxySpec", "./pkg/apis/zaproxy/v1alpha1.ZaproxyStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_zaproxy_v1alpha1_ZaproxySpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZaproxySpec defines the desired state of Zaproxy",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"attackType": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"tragetNamespace": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"tragetIngress": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"attackType", "tragetNamespace", "tragetIngress"},
			},
		},
	}
}

func schema_pkg_apis_zaproxy_v1alpha1_ZaproxyStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ZaproxyStatus defines the observed state of Zaproxy",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"attackStatus": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"attackStatus"},
			},
		},
	}
}
